import { eng } from 'stopword';

/** Messaging / link / attachment noise beyond standard English stopwords. */
const CHAT_TECH_URL_EXTRA = [
  'apk',
  'asp',
  'au',
  'auth',
  'be',
  'bin',
  'bmp',
  'br',
  'ca',
  'caption',
  'captioned',
  'captioning',
  'cn',
  'co',
  'com',
  'de',
  'doc',
  'docx',
  'dmg',
  'epub',
  'exe',
  'facebook',
  'fr',
  'ftp',
  'gif',
  'gmail',
  'google',
  'htm',
  'html',
  'https',
  'http',
  'img',
  'instagram',
  'io',
  'it',
  'jp',
  'jpeg',
  'jpg',
  'mobi',
  'mov',
  'mp3',
  'mp4',
  'msg',
  'net',
  'nl',
  'omit',
  'omitted',
  'org',
  'pdf',
  'php',
  'png',
  'ppt',
  'pptx',
  'rar',
  'telegram',
  'tif',
  'tiff',
  'ttf',
  'twitter',
  'txt',
  'uk',
  'us',
  'vosotras',
  'vosotros',
  'wav',
  'webp',
  'webm',
  'webpage',
  'website',
  'whatsapp',
  'www',
  'xls',
  'xlsx',
  'youtu',
  'youtube',
  'zip',
];

/** Casual chat fillers not in `eng`. */
const CHAT_FILLER_EXTRA = ['btw', 'hello', 'hey', 'hi', 'hiya', 'hmm', 'idk', 'imo', 'lmao', 'lol', 'nope', 'okay', 'omg', 'pls', 'please', 'smh', 'thanx', 'thanks', 'thx', 'yep', 'yeah', 'yo'];

/** Porter “English” list gaps and other very common tokens (>=3 chars for our tokenizer). */
const EXTRA_EN_STOP = [
  'anything',
  'arent',
  'cant',
  'couldnt',
  'didnt',
  'does',
  'doesnt',
  'done',
  'dont',
  'every',
  'everything',
  'hadnt',
  'havent',
  'isnt',
  'lets',
  'nothing',
  'not',
  'nor',
  'no',
  'shall',
  'shouldnt',
  'something',
  'wasnt',
  'werent',
  'will',
  'wont',
  'wouldnt',
  'yes',
  'yet',
];

/**
 * Tokens dropped in "useful" word-cloud mode (lowercase; message tokens are `[a-z0-9]{3,}`).
 */
export const USEFUL_WORD_STOP_SET = new Set<string>([...eng, ...CHAT_TECH_URL_EXTRA, ...CHAT_FILLER_EXTRA, ...EXTRA_EN_STOP]);
